import { ComponentDetails } from "./template-components.interface";

export const components: ComponentDetails[]= [
    {
      id: "1",
      name: "Component 1",
      description: "This is the description for Component 1",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 1",
      tags: ["#tag1", "#tag2"],
    },
    {
      id: "2",
      name: "Component 2",
      description: "This is the description for Component 2",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 2",
      tags: ["#tag3", "#tag4"],
    },
    {
      id: "3",
      name: "Component 3",
      description: "This is the description for Component 3",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 3",
      tags: ["#tag2", "#tag5"],
    },
    {
      id: "4",
      name: "Component 4",
      description: "This is the description for Component 4",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 4",
      tags: ["#tag1", "#tag4"],
    },
    {
      id: "5",
      name: "Component 5",
      description: "This is the description for Component 5",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 5",
      tags: ["#tag3", "#tag5"],
    },
    {
      id: "6",
      name: "Component 6",
      description: "This is the description for Component 6",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 6",
      tags: ["#tag2", "#tag4"],
    },
    {
      id: "7",
      name: "Component 7",
      description: "This is the description for Component 7",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 7",
      tags: ["#tag1", "#tag3"],
    },
    {
      id: "8",
      name: "Component 8",
      description: "This is the description for Component 8",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 8",
      tags: ["#tag2", "#tag5"],
    },
    {
      id: "9",
      name: "Component 9",
      description: "This is the description for Component 9",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 9",
      tags: ["#tag1", "#tag4"],
    },
    {
      id: "10",
      name: "Component 10",
      description: "This is the description for Component 10",
      imagePath: "assets/images/Filter-1-pg1.png",
      details: "Details about Component 10",
      tags: ["#tag3", "#tag5"],
    },
  ];
