import { ComponentDetails } from './template-components.interface';

export const components: ComponentDetails[] = [
  {
    id: '1',
    name: 'Login Form Component',
    description: 'Angular Reactive form with material UI styling',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 1',
    tags: ['#angular', '#forms', '#reactiveforms', '#material'],
  },
  {
    id: '2',
    name: 'Phone Mask Pipe',
    description:
      'A custom Angular pipe to mask phone numbers with hidden and unhidden feature',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details:
      "A custom Angular pipe to mask phone numbers.Provides two transformation methods based on the provided arguments.Only valid for valid UAE phone number length = 12If the argument includes 'hide', the pipe will return a masked phone number with hidden digits.Otherwise, it will return a masked phone number with partial visibility of digits.",
    tags: ['#angular', '#pipes', '#mask', '#maskphone'],
  },
  {
    id: '3',
    name: 'Component 3',
    description: 'This is the description for Component 3',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 3',
    tags: ['#tag2', '#tag5'],
  },
  {
    id: '4',
    name: 'Component 4',
    description: 'This is the description for Component 4',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 4',
    tags: ['#tag1', '#tag4'],
  },
  {
    id: '5',
    name: 'Component 5',
    description: 'This is the description for Component 5',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 5',
    tags: ['#tag3', '#tag5'],
  },
  {
    id: '6',
    name: 'Component 6',
    description: 'This is the description for Component 6',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 6',
    tags: ['#tag2', '#tag4'],
  },
  {
    id: '7',
    name: 'Component 7',
    description: 'This is the description for Component 7',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 7',
    tags: ['#tag1', '#tag3'],
  },
  {
    id: '8',
    name: 'Component 8',
    description: 'This is the description for Component 8',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 8',
    tags: ['#tag2', '#tag5'],
  },
  {
    id: '9',
    name: 'Component 9',
    description: 'This is the description for Component 9',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 9',
    tags: ['#tag1', '#tag4'],
  },
  {
    id: '10',
    name: 'Component 10',
    description: 'This is the description for Component 10',
    imagePath: 'assets/images/Filter-1-pg1.png',
    details: 'Details about Component 10',
    tags: ['#tag3', '#tag5'],
  },
];
